// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sub.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id, service_name, price, user_id, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at, deleted_at
`

type CreateSubscriptionParams struct {
	ID          uuid.UUID  `json:"id"`
	ServiceName string     `json:"service_name"`
	Price       int32      `json:"price"`
	UserID      uuid.UUID  `json:"user_id"`
	StartDate   time.Time  `json:"start_date"`
	EndDate     *time.Time `json:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
UPDATE subscriptions
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at, deleted_at
FROM subscriptions
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSubscriptions = `-- name: GetSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at, deleted_at
FROM subscriptions
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSubscription = `-- name: GetTotalSubscription :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at, deleted_at
FROM subscriptions
WHERE deleted_at IS NULL
  AND start_date >= $1
  AND ($2::timestamp IS NULL OR start_date <= $2)
  AND user_id = $3
  AND service_name = $4
`

type GetTotalSubscriptionParams struct {
	StartDateFrom time.Time        `json:"start_date_from"`
	StartDateTo   pgtype.Timestamp `json:"start_date_to"`
	UserID        uuid.UUID        `json:"user_id"`
	ServiceName   string           `json:"service_name"`
}

func (q *Queries) GetTotalSubscription(ctx context.Context, arg GetTotalSubscriptionParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getTotalSubscription,
		arg.StartDateFrom,
		arg.StartDateTo,
		arg.UserID,
		arg.ServiceName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSubscriptionCost = `-- name: GetTotalSubscriptionCost :one
SELECT COALESCE(SUM(price), 0)::BIGINT AS total
FROM subscriptions
WHERE deleted_at IS NULL
  AND start_date >= $1
  AND ($2::timestamp IS NULL OR start_date <= $2)
  AND user_id = $3
  AND service_name = $4
`

type GetTotalSubscriptionCostParams struct {
	StartDateFrom time.Time        `json:"start_date_from"`
	StartDateTo   pgtype.Timestamp `json:"start_date_to"`
	UserID        uuid.UUID        `json:"user_id"`
	ServiceName   string           `json:"service_name"`
}

func (q *Queries) GetTotalSubscriptionCost(ctx context.Context, arg GetTotalSubscriptionCostParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalSubscriptionCost,
		arg.StartDateFrom,
		arg.StartDateTo,
		arg.UserID,
		arg.ServiceName,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at, deleted_at
FROM subscriptions
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscriptionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET service_name = $2,
    price        = $3,
    start_date   = $4,
    end_date     = $5,
    updated_at   = NOW()
WHERE id = $1
  AND deleted_at IS NULL RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at, deleted_at
`

type UpdateSubscriptionParams struct {
	ID          uuid.UUID  `json:"id"`
	ServiceName string     `json:"service_name"`
	Price       int32      `json:"price"`
	StartDate   time.Time  `json:"start_date"`
	EndDate     *time.Time `json:"end_date"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
