definitions:
  T_internal_api_http_v01_errors.ErrorResponse:
    properties:
      details:
        additionalProperties:
          type: string
        example:
          '"description"': '"must be valid UUID"}'
          '{"field"': '"user_id"'
        type: object
      message:
        example: invalid request
        type: string
      reason:
        example: invalid_guid
        type: string
    type: object
  T_internal_entity.Status:
    enum:
    - new
    - in_progress
    - done
    type: string
    x-enum-varnames:
    - StatusNew
    - StatusInProgress
    - StatusDone
  T_internal_entity.Task:
    properties:
      created_at:
        type: string
      delete_at:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        $ref: '#/definitions/T_internal_entity.Status'
      title:
        type: string
      updated_at:
        type: string
    type: object
  internal_api_http_v01.CreateTaskRequest:
    properties:
      description:
        example: Нужно реализовать CRUD на Fiber
        type: string
      status:
        allOf:
        - $ref: '#/definitions/T_internal_entity.Status'
        description: 'допустимые значения: new, in_progress, done'
        enum:
        - new
        - in_progress
        - done
      title:
        example: Сделать тестовое задание
        type: string
    type: object
  internal_api_http_v01.UpdateTaskRequest:
    properties:
      description:
        example: Добавить больше деталей
        type: string
      status:
        allOf:
        - $ref: '#/definitions/T_internal_entity.Status'
        enum:
        - new
        - in_progress
        - done
      title:
        example: Обновлённый заголовок
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/tasks:
    get:
      consumes:
      - application/json
      description: Пагинированный список задач
      parameters:
      - default: 20
        description: Максимум записей
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - default: 0
        description: Смещение
        in: query
        minimum: 0
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/T_internal_entity.Task'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
      summary: Получение списка задач
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: Создание новой задачи для пользователя
      parameters:
      - description: Тело запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_api_http_v01.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ID созданной задачи
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
      summary: Создать задачу
      tags:
      - Tasks
  /api/v1/tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет задачу по её UUID (мягкое или жёсткое удаление зависит
        от реализации)
      parameters:
      - description: ID задачи (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
      summary: Удалить задачу
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: Возвращает задачу по UUID
      parameters:
      - description: ID задачи (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/T_internal_entity.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
      summary: Получить задачу по ID
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      description: Обновление полей существующей задачи
      parameters:
      - description: ID задачи (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Тело запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_api_http_v01.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/T_internal_api_http_v01_errors.ErrorResponse'
      summary: Обновить задачу
      tags:
      - Tasks
swagger: "2.0"
